### ISSUE TITLE
Install on Drupal 8.8.1 / 8.8.2-dev

### ISSUE THREAD

**Issue by thecaribbean** [ahebrank/media_entity_kaltura#2]
I was excited about this module and must praise the work done so far.

I installed as follows:

`composer require drupal/media_entity_kaltura`

Got: Package operations: 3 installs, 0 updates, 0 removals
  - Installing drupal/entity (1.0.0-rc3): Downloading (100%)         
  - Installing drupal/media_entity (1.8.0): Downloading (100%)         
  - Installing drupal/media_entity_kaltura (dev-1.x d7c3c76)

Then tried to enable using drush

`vendor/bin/drush en media_entity_kaltura`

The following module(s) will be enabled: media_entity_kaltura, media_entity, entity

but then got the following error

"In PreExistingConfigException.php line 65:
Configuration objects (system.action.media_delete_action, system.action.media_publish_action, system.action.media_save_action, system.action.media_unpublish_action, views.view.  
  media) provided by media_entity already exist in active configuration"

Drupal Version 8.8.2-dev
Composer version 1.9.1
Drush Commandline Tool 10.1.1
PHP 7.3.11-1

Any thoughts?

**Comment by ahebrank** [comment]
This module is waiting for an update to support core's `media` module that landing in Drupal 8.4. Unfortunately I don't have any active projects using this so it's not gotten attention from me -- other users have put in some work over on https://www.drupal.org/project/media_entity_kaltura/issues/2962172 so I'd encourage you to try the patches and follow up over there.
